### ISSUE TITLE
Steam Deck Support

### ISSUE THREAD

**Issue by AlexMKramer** [Souzooka/Dead-Rising-TimeSkip#1]
I have been using this script on Windows and it works great.  Recently got the Steam Deck and wanted to speedrun the game on the go.  Unfortunately, the script is unable to locate the process when running on the Steam Deck through Proton.  

I have tested it by running it within the same prefix, but it still isn't able to find the game process. 

I would love to be able to run it on the Deck, any help is appreciated!

**Comment by Souzooka** [comment]
Hi Alex, this is a rather old project, and I don't know about how compatible it is with Proton/Linux, but you might want to check out this line here -- https://github.com/Souzooka/Dead-Rising-TimeSkip/blob/389fb0d8397f2105f10260bd7949b0150d1d7b68/App/DR%20RTM/DR%20RTM/Form1.cs#L82

That ends up using this method https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.getprocessesbyname?view=net-6.0#system-diagnostics-process-getprocessesbyname(system-string) to locate the processes.

**Comment by AlexMKramer** [comment]
Researching it further, I found that it is because Proton runs programs in their own containers.  Once the game is loaded, that container is locked.  So, trying to open another program in the same prefix doesn't open it in the same container and it cannot see outside processes.  

Printing out a list of the processes from Get.Processes() spits out only the ones running within the same container.

**Comment by AlexMKramer** [comment]
I have got it working now.  Took a bit of trial and error, but the solution turned out to be really easy.  Updating in case anyone else comes looking later for this super niche scenario.  Sadly it only works properly in Desktop mode.  When run in Gaming mode it opens one application then the other on top of it.  I don't know of a way to switch which window is on top in gaming mode.  

When launching the game from steam, you can set launch options for it.  In order for the game and the TimeSkipTool to run in the same prefix, you have to add a launch option that stops Steam from launching the game AFTER it sets the prefix.  We also want it to launch a script to run both programs.

Here is my solution:

## Script
You will need the script and the mod in the same directory as your DeadRising.exe and you will need to set the correct permissions for the script.  

The script looks like this for me.  The Steam Deck may use a different version of Proton in later updates, so YMMV.  

`#!/bin/bash`
`"home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton" run DeadRising.exe & "home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton" run DeadRisingSpeedrunningSkipTool.exe`

Then change the permissions on it:

`chmod 755 script`

Then move it to your Dead Rising folder.  You can find it in Steam by right clicking on Dead Rising in your library, clicking Local Files, and Browse...

## Launch option
Go into your Steam library and right click Dead Rising, then click Properties.  Then in General, in the box under Launch Options enter:

`./script && echo %command% >/dev/null`

With that set as your launch option, it will run the script and throw away whatever steam is trying to run after.  
## Closing
With this it all runs as it normally would on Windows.  I haven't tried it, but I assume LiveSplit also works.
